### ISSUE TITLE
Haproxy 2_4?

### ISSUE THREAD

**Issue by cidrbl0ck** [sweenig/lm#1]
Hey Stuart, You commented on an LM forum post I made last year concerning a better DS for Haproxy. I'm wondering if you still have that DS you wrote? I checked the official LM Repo from within LM itself, and only the old one exists.
Any chance I could get that from you again?
Thanks!

**Comment by sweenig** [comment]
This is that one. The older one used SNMP extensions and relied on changing the server's SNMP config. This one requires minimal, if any, changes to the HAproxy server.
